# Site settings
title:          KCNET KGURU
description:    "KCNET KGURU Tech Blog"
baseurl:        "/tale"
url:            "https://kcnet-kguru.github.io/ "

# Google Analytics
google_analytics: UA-168993046-1

# Author
author:
  name:         KCNET
  url:          http://www.kcnet.co.kr
  email:        jsi@kcnet.co.kr

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

remote_theme: chesterhow/tale
  
# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-remote-theme
  # - jemoji #Uncomment this to allow emoji in your post

theme:      tale

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale